- name: Download EPUB and validate
  run: |
    mkdir -p work
    curl -L "${{ inputs.epub_url }}" -o work/book.epub
    python3 -c "import sys,zipfile; p='work/book.epub'; 
import traceback
try:
    zipfile.ZipFile(p).testzip()
    print('EPUB OK:', p)
except Exception as e:
    print('ERROR: not a valid EPUB/ZIP ->', e); sys.exit(1)"
